services:
  - type: web
    name: telegram-miniapp-store
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: SECRET_KEY
        value: supersecret
      - key: ADMIN_PASSWORD
        value: 1234
    plan: free
